### ISSUE TITLE
typeDescription(x) blows up if x is null or undefined

### ISSUE THREAD

**Issue by no-man-is-an-island** [deckchair-technicians/vicets#9]
.. so the error message is confusing

**Comment by no-man-is-an-island** [comment]
```
TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Object.typeDescription (@deckchair-technicians/vice/src/impl/util.ts:64:18)
    at predicate (@deckchair-technicians/vice/src/schemas.ts:38:41)
    at DelegatingSchema.schema [as delegatedConform] (@deckchair-technicians/vice/src/schemas.ts:76:48)
   ```
